name: "Build Latest Image"
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'gh-runner-devcontainer/**'
      - '!gh-runner-devcontainer/README.md'
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:gh-runner-devcontainer"
          push: true
          tags: benthebuilder/gh-runner-devcontainer:latest