<<<<<<< HEAD
name: "Build github-runner-build [Latest]"
=======
name: "Build Latest Image: Repo Level Runner"
>>>>>>> main
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'github-runner-build/**'
      - '!github-runner-build/README.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:github-runner-build"
          push: true
          tags: benthebuilder/cglabs-gh-runner:latest